### ISSUE TITLE
Kenteken-pls option is not displayed when right click a focused input field on Firefox

### ISSUE THREAD

**Issue by sudo-plz** [Droeftoeter/kentekenpls-ext#22]
OS: Ubuntu Budgie 20.04
Browser: Mozilla Firefox 85.0.1
Kentekenpls version: 1.3.0
Other extensions: None enabled

Shortcut alt+shift+k works fine, right click does not show the option unfortunately.

**Comment by Droeftoeter** [comment]
Fixed in v1.3.1
